export ZSH_DIR=$HOME/.dotfiles/zsh

# Main configuration
export ZSH="/Users/olive/.oh-my-zsh"
export NVM_LAZY_LOAD=true
export NVM_COMPLETION=true
ZSH_THEME="sorin"
DEFAULT_USER=olive
DISABLE_AUTO_UPDATE="true"
plugins=(zsh-nvm evalcache git colored-man-pages vi-mode tmux zsh-autosuggestions)
bindkey '  ' autosuggest-accept
source $ZSH/oh-my-zsh.sh

export EDITOR=nvim
export FZF_DEFAULT_COMMAND='rg --files'
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd

# Keep history per session
setopt no_share_history
unsetopt share_history

# Specific config files
source $ZSH_DIR/zsh-alias
source $ZSH_DIR/zsh-kubectl

# Local
source ~/.zshrc-local
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
