# uncomment for profiling
#zmodload zsh/zprof

# aliases
source $ZSH_DIR/zsh-alias

# options
setopt no_share_history
unsetopt share_history

# vim mappings
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# vi mode
# set -o vi

# vim edit command line
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# emacs style
bindkey '^P' up-line-or-search

# completion
source $ZSH_DIR/completion/completion.zsh

# nvm
source $ZSH_DIR/zsh-nvm

# prompt
source $ZSH_DIR/zsh-prompt

# local
source ~/.zshrc-local

#zprof > /tmp/zprof
